# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Louis Boyle
tagline:          'MEAN Full Stack Developer'
description:      'MEAN Full Stack Developer'
url:              http://lboyle.github.io
baseurl:          /

author:
  name:           'Louis Boyle'
  url:            https://twitter.com/BrittleSkydiver

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/LBoyle/LBoyle.github.io

gems: [jekyll-paginate]
